# 指定 Github Actions 的运行环境为 Ubuntu 20.04
name: shellingfordly blog
on:
  push:
    branches:
      - master
env:
  NODE_ENV: production
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2

      # 安装 Node.js 和项目依赖
      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: pnpm install

      # 打包项目
      - name: Build
        run: pnpm run build

      # 部署到 GitHub Pages（可选）
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
